{% set name = "eli5" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aea7b51be9157ce615b319711467f358de03da12328e5639818b3cb3755aa056

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - attrs >16.0.0
    - jinja2
    - numpy >=1.9.0
    - scipy
    - singledispatch >=3.4.0.3
    - six
    - scikit-learn >=0.18
    - python-graphviz
    - tabulate >=0.7.7

test:
  imports:
    - eli5

about:
  home: https://eli5.readthedocs.io/
  license: MIT
  license_file: LICENSE.txt
  summary: Debug machine learning classifiers and explain their predictions
  description: |
    ELI5 is a Python package which helps to debug machine learning classifiers
    and explain their predictions.
  doc_url: https://eli5.readthedocs.io/en/latest/
  dev_url: https://github.com/TeamHG-Memex/eli5/

extra:
  recipe-maintainers:
    - rmax
    - xhochy
