travis:
  secure:
    BINSTAR_TOKEN: bNWMjdfyWIKtoFbqoVgfdOTqz7oDr/CuF95mNlCXRmVzCpC42xeTigjUmdX6dBNmY/gtytsimi8vqj4Ody0bqWA9Acgv5+tiiJVvCXxM/7C95zix7o7sXNfoj+fBQYB7GsLmNIxm8ju/+euc0xYsb6Dl3uiZCyqC5iI0moLJ9s6dOD28cwm+1skylHIKU947K2A8HmQF/uxo9mbWmH85WgyVwNqjJax+sOKKy+pSs62JGZpRPVt8KpuOrZYfwyrkEPrYZyQtBRQN2wCyfUHFegnBMU/Rf30dutmCWIThh7wQuxdE24Zs4NBdSfCcMofdP/+oDADrwPRDX9fO0HUeF/l+SsKlQPdlR3qE2t9qR6KIG+HI/GT3jrouTX3ICQN8mW2+H1j2oRqeLyPUuM8aQ+uA0Pq3v38KtkZpXNMpLLA2tszvCAMG3tR3U5o/AfV/I9D+mnQp1oH5rpvIWTCclJmOH+VzOJbVzbB/9IonawuxqEFuahpgysl/yNZNUF472hk/lC/j69nXhOCcZO2u10BuDisPpoBl9xpKj2XwuFJCU/3ZWwAIWuBkAGv0WgG2vIUo8KGMQIOaTipITWZ3rIAaz0G0ekcVNzeeMD68nUjLcAMH79pGrGSKzv68fdxuKES7gyIV++A+1dW1vDY0N/o507Ipqqc4gI6rSuYVw0s=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
