travis:
  secure:
    BINSTAR_TOKEN: V+yNK7rbmZy4m/Gjme3ijf+JdAMbXqCjHXBp29bTKnNKgVh1V+PzS+2c8Cob6znzBucA97TCY3ZQ9llxWIuaqElOqGDeX7InsA36w978+iPHigpKZkkrvVNJzvZ/Yj9HXaz+HCYSn8fxBnpem0uCsPL79UlEfQvs/24w0zxaNRtEEzcT9U7fAJD4hML4iGaI7HM1EmTw7tUjgg52RwZYAkMVtJzjPbBXn7XtCuDT5+MuKhgD5PQVzlzXdllm70jeVzXa5XFedmh1iLdgA7G40G/2OiGX0TCFeBkopQDSgNmZ/e4EBUfh8Y2DFVPXuD0LWhpIfsi/oQjwUBe1Ac2BrnDx1BQC67MonYKZp5X5t7lWUOtCMIx7ZWdvuKAmOF9dFvlH/IEznwo2gfhNqf9Owg6vmtiRYq8OHq4rCEo3p9C7bcompWMCm2+i49osjZvVFWkdYI2tZmHbW9+uc1bovTKpMEh1BCzPON8g9TyEWYxNIfPw3To2UFJWjJCqcfHuoq2rxrUa56ylzpyXuMVJj29cInEyQXh442Y29KjYGBJwXt4sBiWgddljos55oIG30E7W2sWaGsfCYcUhwDUwKy2yEkFvKRQTWrGIgPZVo9qNqALpQ67pQCK+zLnMVSLWVJEeYgwvf982qG4IUZY0EzWUJ74o9sUOrgvtppGRzO0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
