travis:
  secure:
    BINSTAR_TOKEN: QOkBCxLPC2A7q3cB/NhtRu1TpOIKk8mOqnS22Cxuen0DbDXtwoOTnEY1mzsu/899BaPZsUgx7Czndz5SMd+ibeEiA/r/dKN7tlOrzogGHZRs5r78ByJYmnQgFZpQdOeMig4bw1+qyzL26xqkvxzjeWcJSxzJhEsmrpqPai/pSbB1erjiZ8j22WSMFPMvkRvA9eCMPIHktGTyGO2Sb30UXOh1Hl/Da/+ffaQWhBJRRgL78EWX0Cts08kvZrLoiHoECSUEWaBamcCF7d5Qgmt1sD+Yq5hu8Z53YaAk+G+n29OezGt4nLh3GK2bYzESZRc1RPaL3Nn+gdWjcdt/MBRQLgCmnEFy6qYossgD4IEaCQbnowXig5lVU3y4TKaXKdCqMRsfjs4pJgt5gtogdEnH364jXBRy0J2/HC5QtBcSNNBgZHg6nSRiDcj39c2hgZC0/xvSRY9XejS1rQdVrpA4f8vvfLoQkD18E3HExCHCM9+Qn4DevsDXJKp2DGrAaOUlV9evZ6HzDxjTJYV3Y9FWrSVz6PL3B0xy3+bG84usW1AV03cRH5Y8I5U4zyASzzAiZJV0V/djsNmDptpiqWXukstOI2CR7GdFo2U95PuYZWWWv0rwT9f4XCnjvALLEHfW9UJqIsBCBNzL8KhGRAa+CgEjLQIrM64ZvDeyoavOttM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
